### ISSUE TITLE
Please add Licence to Project

### ISSUE THREAD

**Issue by puerile** [aybe/Windows-API-Code-Pack-1.1#11]
Please add a licence file or something similar, as the link to the licence on Microsoft's NuGet platform is broken.

**Comment by jozefizso** [comment]
:+1:

**Comment by ForNeVeR** [comment]
License does not seem to be available in any form from Microsoft. What can we do? Is it legal to take the latest copy from the Web Archive?

**Comment by shanselman** [comment]
Ping

**Comment by johnkoerner** [comment]
From looking at this code, it appears it is based off the codepack samples that used to be available from code.microsoft.com. I don't know if @aybe is associated with Microsoft.  If not, I don't think they can rightfully put a license on this project. The [source (original)](https://github.com/aybe/Windows-API-Code-Pack-1.1/tree/master/source%20(original)) folder appears to contain the original download that you used to be able to obtain from Microsoft.

**Comment by ForNeVeR** [comment]
Original code had a license: http://web.archive.org/web/20130717101016/http://archive.msdn.microsoft.com/WindowsAPICodePack/Project/License.aspx

But it is no longer accessible from Microsoft site.

**Comment by ForNeVeR** [comment]
> I don't know if @aybe is associated with Microsoft. If not, I don't think they can rightfully put a license on this project. 

Please note that point of this issue is not assigning the **new** license, but simply clarifying about the existing one (that was initially published by Microsoft, but no longer accessible in any of the official sources).

**Comment by aybe** [comment]
Hi !

Sorry for the delay, I wasn't watching the repo ...

I finally started fixing bugs, there are people that are sending PRs but I can't simply merge them as-is, need to look/test/decide/etc first. Hope to release a new package ASAP.

Adding a licence using the web archive link sent by @ForNeVeR seems the way to go, what do you guys think ?

Thanks

Note: I'm not affiliated with Microsoft

**Comment by ForNeVeR** [comment]
@aybe personally I'd say that definitely the best course of action is to clarify the license from Microsoft. Maybe try to contact them somehow? _(Honestly, I've tried to find the support email on their site and haven't found it. It seems that they have a very strange politics regarding email support.)_

**Comment by aybe** [comment]
I've just added the original licence and updated the readme:

https://github.com/aybe/Windows-API-Code-Pack-1.1
https://github.com/aybe/Windows-API-Code-Pack-1.1/blob/master/LICENCE

If Microsoft feels something is wrong, I guess they will get in touch by themselves :)
