### ISSUE TITLE
Need a little bit of help

### ISSUE THREAD

**Issue by nisad** [aybe/Windows-API-Code-Pack-1.1#17]
Hi aybe,
It's not the issue per se I am trying to use part of this code to create something for me. I will really appreciate any help. I would like to have ExplorerBrowser with a tree only and ability to filter by collection of extensions. I am able to do it with CustomFileDialog but I need it with ExplorerBrowser .
Do you have any suggestion how I can achieve this?
Best regards,
Nisad.

**Comment by aybe** [comment]
Sorry but I have no idea, I'd suggest you to ask at StackOverflow to reach a wider audience.
